### PR TITLE
Add artifacts for ppc64le and s390x

### LINKED ISSUE #73: Any Chance of getting registry running on s390
Is there any chance to get a registry container running on s390x architecture?

### LINKED ISSUE #95: ppc64le support in multi-arch image
The multi-arch image for docker registry, https://hub.docker.com/_/registry, doesn't have the reference to `ppc64le` image. 

We will like to add the support for `ppc64le` architecture as well for this image.

### PR DESCRIPTION
**Pull request by yselkowitz**
This is an alternative to #124 should you not wish to go down that route yet.

Closes #95
Closes #73

### CODE REVIEW

**Comment by yselkowitz** [comment]
cc @dmcgowan any preference of this or https://github.com/docker/distribution-library-image/pull/124 in order to enable ppc64le and s390x builds?

**Comment by milosgajdos** [comment]
@yselkowitz we've updated the image in the following PRs:
* #129 
* #130 
* #131 

The image is also already available on Hub as a multiarch official image (see [here](https://hub.docker.com/layers/registry/library/registry/2.8.0-beta.1/images/sha256-15ef405da19611db38d95617a7ca4f842a6a3d1f32fd8106249ba8d4b171cbca?context=explore))

Would you mind if I close this PR and #124 which are basically duplicates at this point?

**Comment by yselkowitz** [comment]
Thank you for that, much appreciated.  Probably not a blocker, but any idea when 2.8.0 will be stable?

**Comment by milosgajdos** [comment]
Don't have exact date but we are aiming for next week or two the latest

**Pull request closed without merging**
