### PR TITLE
support arm64 architecture

### PR DESCRIPTION
**Pull request by longquan7**
I was used the Dockerfile to build image successed,so I think we can pull it to the https://hub.docker.com/u/arm64v8/

### CODE REVIEW

**Comment by longquan7** [comment]
I wonder if you are supportive this image for arm64 architecture

**Comment by lag-linaro** [comment]
Still waiting on #74

**Comment by lag-linaro** [comment]
Looks like this can be closed now.

**Comment by dmcgowan** [comment]
Support added

**Pull request closed without merging**
