### PR TITLE
Multi-Arch Builds via Multi-Stage

### LINKED ISSUE #54: support arm64 system
I was modify the Dockerfile the first line in order to support arm64.
Change "From alpine:3.5" to "From aarch64/alpine:3.5" that would support arm64 system. So How to use one Dockerfile to support different syatem than x86 and arm64.

### LINKED ISSUE #73: Any Chance of getting registry running on s390
Is there any chance to get a registry container running on s390x architecture?

### LINKED ISSUE #78: registry image won't run on arm64v8
I am trying to install registry on a Raspberry Pi 3 B + running the arm64v8 version of hypriot. The registry will not run.

## Docker info
```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 18.04.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.37-hypriotos-v8
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: aarch64
CPUs: 4
Total Memory: 969MiB
Name: black-pearl
ID: xxxx
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 os=linux
 arch=arm64
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support

```
I first tried to run:

```
docker run -d -p 5000:5000 --restart always --name registry registry
Unable to find image 'registry:latest' locally
latest: Pulling from library/registry
docker: no matching manifest for linux/arm64 in the manifest list entries.
See 'docker run --help'.
```
Noticed on hub.docker.com that there is a registry for aarch64 and tried:
```
docker run --platform linux/aarch64 -d -p 5000:5000 --restart always --name registry registry
Unable to find image 'registry:latest' locally
docker: Error response from daemon: invalid platform: invalid platform architecture "aarch64".
See 'docker run --help'.
```

### LINKED ISSUE #95: ppc64le support in multi-arch image
The multi-arch image for docker registry, https://hub.docker.com/_/registry, doesn't have the reference to `ppc64le` image. 

We will like to add the support for `ppc64le` architecture as well for this image.

### LINKED ISSUE #101: Multi-arch builds via Multi-Stage Dockerfile
I been digging through a couple of the issues/PRs pertaining multi-arch builds. It looks like https://github.com/docker/distribution-library-image/pull/74 raised by @tianon was a good solution. 

From reading the messages on the PR I am a confused as why it got closed. @davidswu or @dmcgowan care to weigh in on that? Was it because PR https://github.com/docker/distribution-library-image/pull/81 and that the official Docker Images pipeline did not allow for multi-stage builds?

It looks like now that official Docker Images pipeline does now support multi-stage builds, https://github.com/docker-library/official-images/issues/3383#issuecomment-521424671. @tianon can you confirm that?

If the official Docker Images pipeline does now support multi-stage builds, I would very much like to see this repository switch over to a multi-stage build. First stage would build the binaries and then the second stage would copy the binaries into the final container. 

@yosifkit’s comment here, https://github.com/docker/distribution-library-image/pull/83#issuecomment-444320937, makes a good point about not having the artifacts in the repository. 

I would really like to see builds for `s390x` and `ppc64le`. Seems like I am not the only one either, https://github.com/docker/distribution-library-image/issues/95, https://github.com/docker/distribution-library-image/issues/73, and https://github.com/docker/distribution-library-image/pull/74#issuecomment-613523767. 

I think supporting multi-arch builds would be accomplished best by implementing a multi-stage Dockerfile.

### PR DESCRIPTION
**Pull request by james-crowley**
This PR is meant to add support for `s390x`, `ppc64le`, `arm64` and any other arch. This is one possible solution to fix #101. 

This PR also fixes a couple other issues as well:

Fixes #95 
Fixes #73 
Fixes #78 
Fixes #54 

Using a multi-stage build will avoid having to upload new `registry` binaries to this repo. 

Most of this PR is based off of @tianon's PR #74, but with a couple updates.

### CODE REVIEW

**Comment by james-crowley** [comment]
@dmcgowan When you get a second, you mind looking over this PR? Happy to make any changes that are needed.

**Comment by dmcgowan** [comment]
The go versions have to line up with the releases. Ideally the dockerfile would just be included in the release or derived directly from it. In these cases, I am fine as long as it is building the same binaries by using the same go version. If a go version update is needed, that has to be treated as a fix not just automatic update.

I defer to @tianon on whether multi stage builds can be used, I have always been OK with it as long as the official build process supports it.

**Comment by dmcgowan** [comment]
Yes, I am open to that, have considered as a part of the 2.8 release. I am always hesitant to release binaries on platforms that we don't have CI infrastructure to test on that platform

**Comment by james-crowley** [comment]
@dmcgowan I see a `.travis.yml` file in that repo, are you guys using Travis CI for your CI? If so, Travis now support `s390x`, `ppc64le` and `arm64`. See [here](https://docs.travis-ci.com/user/multi-cpu-architectures/#testing-on-multiple-cpu-architectures) for Travis docs.

If you guys are not using Travis, what CI infrastructure are you using? IBM does offer free resources, `s390x` and `ppc64le`, to open source communities. If you are interested, I can point you in the direction so you are not publishing binaries for platforms you can not test.

**Comment by clnperez** [comment]
@dmcgowan if memory serves me correctly, there are some registry tests in moby ci -- and power and z do have jobs there (e.g. https://ci-next.docker.com/public/blue/organizations/jenkins/moby/detail/PR-41155/3/pipeline). It's not *the* distribution CI but it's not nothing. :D

**Comment by clnperez** [comment]
Any news here?

**Comment by james-crowley** [comment]
@clnperez Thanks for the ping! Sometimes PRs can get lost in my other projects! It looks like we are still waiting for @dmcgowan.

@dmcgowan Is this something you are willing to relook at? I am happy to update the PR with any new updates/features you need.

**Comment by milosgajdos** [comment]
@james-crowley  we've updated the image in the following PRs:
* #129 
* #130 
* #131 

The image is also already available on Hub as a multiarch official image (see [here](https://hub.docker.com/layers/registry/library/registry/2.8.0-beta.1/images/sha256-15ef405da19611db38d95617a7ca4f842a6a3d1f32fd8106249ba8d4b171cbca?context=explore))

You can find all the artifacts on the pre-release page in GH https://github.com/distribution/distribution/releases/tag/v2.8.0-beta.1

Would you mind if I close this PR and #124 which are basically duplicates at this point?

**Comment by mkumatag** [comment]
Finally...!, thanks for this wonderful news folks..

**Pull request closed without merging**
