### PR TITLE
Support arm and arm64 binaries for v2.6.2

### PR DESCRIPTION
**Pull request by dmcgowan**
Updates the `update.sh` script to support cross compiling binaries. Uses an updated 2.6 commit in upstream distribution with support for GOARCH as a build arg.

Each architecture creates a directory based on the `GOARCH` value and copies the Dockerfile, binary, config, and entrypoint to keep the docker build self contained to the directory for a given architecture.

### CODE REVIEW

**Comment by tianon** [comment]
I would highly recommend setting an explicit `GOARM` value for `GOARCH=arm` -- `7` if targeting Debian, `6` if targeting Alpine (which I believe this is, right?)

See also https://github.com/golang/go/wiki/GoArm, especially:

> In cross compilation situations, it is recommended that you always set an appropriate GOARM value along with GOARCH.

**Comment by dmcgowan** [comment]
Updated to include GOARM and registry default set to GOARM=6 for the alpine based Dockerfile used to build the binary

**Comment by lag-linaro** [comment]
Did anyone actually test this?  Not sure I understand how it could have worked.

`alpine:3.4` is not a suitable base for AArch64 since support wasn't added until `alpine:3.6`.

**Comment by lag-linaro** [comment]
When changing to a suitable base, I also get:

```
$ docker run -ti --rm 29a18114e28f
<exit with no output>
```
Strange.
```
$ docker run -ti --rm 29a18114e28f sh
/ # registry 
Segmentation fault (core dumped)
```

**Comment by dmcgowan** [comment]
@lag-linaro the binaries were checked, not with that alpine version. Just verified with alpine 3.8. I am going to make an updated PR, do you might testing that as well after I open it?

**Pull request merged**
